//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heathweb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Appointment
    {
     
        public int Patient_ID { get; set; }

        [Display(Name = "Name")]
        public string Patient_Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Message { get; set; }
        [Display(Name = "Appointme Date")]
        public Nullable<System.DateTime> Appointment_Date { get; set; }
        public Nullable<int> Doctor_ID { get; set; }
    
        public virtual tbl_Doctor tbl_Doctor { get; set; }
    }
}
