//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heathweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Doctor()
        {
            this.tbl_Appointment = new HashSet<tbl_Appointment>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Department_ID { get; set; }
        public string DoctorName { get; set; }
        public string ImgURL { get; set; }
    
        public virtual tbl_department tbl_department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Appointment> tbl_Appointment { get; set; }
    }
}
